"use client";
import React, { useState } from "react";

const cereals = [
  {
    marca: "kellogg's",
    nombre: "Corn Flakes",
    descripcion: "Hojuelas de maíz tostada",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "kellogg's",
    nombre: "kellogg's Zucaritas",
    descripcion: "Hojuelas de maíz azucararadas",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "kellogg's",
    nombre: "kellogg's Choco krispis pops",
    descripcion: "Cereal de maiz inflado con sabor a chocolate",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Maizoritos",
    nombre: "Maizoritos Fruty aros",
    descripcion:
      "Cereal Azucarado a base de maíz, trigo y avena con sabor a frutas",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Maizoritos",
    nombre: "Maizoritos Avena Aros",
    descripcion: "Cereal expandido a base de avena",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Maizoritos",
    nombre: "Maizoritos Cronch Flakes",
    descripcion: "Hojuelas de maíz tostado",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Maizoritos",
    nombre: "Maizoritos Azucaradas",
    descripcion: "Hojuelas de Maíz Azucaradas",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Mairzoritos",
    nombre: "Mairzoritos Natural MIx",
    descripcion: "Cereal de maíz azucarado con canela, granola y almendras",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Maizoritos",
    nombre: "Maizoritos Choco Safari",
    descripcion:
      "Cereal expandido achocolatado a base de maíz, arroz, trigo y avena.",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Maizoritos",
    nombre: "Maizoritos Pop cronch",
    descripcion:
      "Cereal expandido azucarado a base de maíz trigo y avena con sabor a chocolate",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Sindoni",
    nombre: "Sindoni Nucita Crunch",
    descripcion:
      "Cereal expandido a base de Maíz y arroz relleno con crema de chocolate Nucita",
    nacional: true,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Tu cereal",
    nombre: "Tu cereal Mega Aros Miel",
    descripcion: "Cereal Expandido a base de maíz y arroz con miel",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Tu cereal",
    nombre: "Tu cereal Mega Klakes",
    descripcion: "Hojuelas de maíz tostado",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Tu cereal",
    nombre: "Tu cereal Mega Bol",
    descripcion: "Cereal expandido a base de maiz con sabor a chocolate",
    nacional: false,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Tu cereal",
    nombre: "Tu cereal Mega Aros",
    descripcion:
      "Cereal expandido a base de maíz y arroz con sabor a frutas tropicales saborisado artificialmente.",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Venepan",
    nombre: "Venepan Choko Bolitos",
    descripcion: "Cereal inflado de maíz y avena con sabor a chocolate",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Venepan",
    nombre: "Venepan Aitos con miel",
    descripcion:
      "cereal inflado con miel enriquecido con vitaminas y minerales",
    nacional: false,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Alimentos Santorini",
    nombre: "Alimentos Santorini Space Pop",
    descripcion:
      "Cereal Expandido a base de arroz maíz  y avena enriquecido con vitaminas y minerales con sabor a vainilla",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Alimentos Santorini",
    nombre: "Alimentos Santorini Planet Fruit",
    descripcion:
      "Cereal Expandido a base de arroz maíz  y avena enriquecido con vitaminas y minerales con sabor a vainilla",
    nacional: false,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Mah pure love",
    nombre: "Mah pure love Avena",
    descripcion:
      "Cereal infantil instantaneo a base de avena enriquecido con vitaminales y minerales, sin azucares añadidos",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Alivensa",
    nombre: "Alivensa Holy Krunch",
    descripcion: "Cereal Copos finos de maíz tostados",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "kellogg's",
    nombre: "kellogg's Corn Flakes",
    descripcion: "The original & best , no artificial color of flavors",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "kellogg's",
    nombre: "kellogg's Frostel Flakes Of corn de maíz Chocolate Milkshake",
    descripcion: "Con sabor natural y artificial, chocolatee milkshake makes",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "kellogg's",
    nombre: "kellogg's  Frostel Flakes of corn de Maíz Cinna Mon",
    descripcion:
      "con sabor natural y artificial, Bursting whit Cinnamon sweetnss",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "kellogg's",
    nombre:
      "kellogg's Frostel Flakes of corn de Maíz Strawberry Milkshake/ Cereal",
    descripcion:
      "con sabor natural y artificial, Makes deliciuous STRAUBERRY flavored milk",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "kellogg's",
    nombre:
      "kellogg's Frostel Flakes  Of Corn whit vanilla flavored marsh mallows",
    descripcion:
      "whit vaniilla flavord marsh mallows naturally & artificially flavored",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "kellogg's",
    nombre: "kellogg's Frostel Flakes of corn de Maíz",
    descripcion: "of corn de Maíz / Cereal",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "kellogg's",
    nombre: "kellogg's Froot Loops",
    descripcion:
      "Natural Fruit Flawors , sabores de frutas naturales , sweetened multigrain cereral",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "kellogg's",
    nombre: "kellogg's Special Made with Yogurty oat clusters/ Cereal",
    descripcion:
      "Strawberry & vanilla naturally flavored wiht other natural flavors",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Carozzi",
    nombre: "Carozzi Vivo Granola",
    descripcion:
      "Cereal para el desayuno a base de avena, trigo, centeno, almendras y miel.",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "FLIPS",
    nombre: "FLIPS",
    descripcion:
      "Cereal expandido a base de arroz, trigo y avena con relleno sabor a chocolate",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "HERO BABY",
    nombre: "HERO BABY",
    descripcion: "Arroz, sin azucares añadidos",
    nacional: false,
    importado: true,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Nestle",
    nombre: "Nestle CEREAL",
    descripcion:
      "Alimento vitaminado compuesto de trigo, solidos totales de leche entera y azucar",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
  {
    marca: "Primor",
    nombre: "Primor crerma de arroz",
    descripcion: "Harina de arroz enriquecida con vitaminas y minerales",
    nacional: true,
    importado: false,
    tamanoRacion: "",
    proteinas: "",
    proteinasNorma: "",
    grasaSaturadas: "",
    grasaSaturadasNorma: "",
    azucares: "",
    azucaresNorma: "",
    sodio: "",
    sodioNorma: "",
    idioma: "",
  },
];

export default function CerealTable() {
  const [filtro, setFiltro] = useState("");

  const filtrados = cereals.filter(
    (cereal) =>
      cereal.nombre.toLowerCase().includes(filtro.toLowerCase()) ||
      cereal.marca.toLowerCase().includes(filtro.toLowerCase())
  );

  return (
    <div className="p-4">
      <input
        type="text"
        placeholder="Buscar por marca o nombre"
        className="border p-2 mb-4 w-full"
        value={filtro}
        onChange={(e) => setFiltro(e.target.value)}
      />
      <table className="table-auto w-full border">
        <thead>
          <tr className="bg-gray-200 text-xs">
            <th className="border px-2 py-1">Nº</th>
            <th className="border px-2 py-1">Marca</th>
            <th className="border px-2 py-1">Cereal de desayuno</th>
            <th className="border px-2 py-1">Descripción</th>
            <th className="border px-2 py-1">Nacional</th>
            <th className="border px-2 py-1">Importado</th>
            <th className="border px-2 py-1">Tamaño de la ración</th>
            <th className="border px-2 py-1">Proteínas</th>
            <th className="border px-2 py-1">Proteínas según Norma</th>
            <th className="border px-2 py-1">Grasa saturadas</th>
            <th className="border px-2 py-1">Límite grasa saturada Norma</th>
            <th className="border px-2 py-1">Azúcares</th>
            <th className="border px-2 py-1">Límite azúcares Norma</th>
            <th className="border px-2 py-1">Sodio</th>
            <th className="border px-2 py-1">Límite sodio Norma</th>
            <th className="border px-2 py-1">Idioma</th>
          </tr>
        </thead>

        <tbody>
          {filtrados.map((cereal, index) => (
            <tr key={index} className="text-center">
              <td className="border px-4 py-2">{index + 1}</td>
              <td className="border px-4 py-2">{cereal.marca}</td>
              <td className="border px-4 py-2">{cereal.nombre}</td>
              <td className="border px-4 py-2">{cereal.descripcion}</td>
              <td className="border px-4 py-2">
                {cereal.nacional ? "Sí" : "No"}
              </td>
              <td className="border px-4 py-2">
                {cereal.importado ? "Sí" : "No"}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
